export const TIMEZONES = [
  { label: "UTC", value: "UTC" },
  { label: "US/Eastern (ET)", value: "America/New_York" },
  { label: "US/Central (CT)", value: "America/Chicago" },
  { label: "US/Mountain (MT)", value: "America/Denver" },
  { label: "US/Pacific (PT)", value: "America/Los_Angeles" },
  { label: "US/Alaska", value: "America/Anchorage" },
  { label: "US/Hawaii", value: "Pacific/Honolulu" },
  { label: "Canada/Atlantic", value: "America/Halifax" },
  { label: "Canada/Newfoundland", value: "America/St_Johns" },
  { label: "Canada/Yukon", value: "America/Whitehorse" },
  { label: "Europe/London (GMT)", value: "Europe/London" },
  { label: "Europe/Paris (CET)", value: "Europe/Paris" },
  { label: "Europe/Berlin", value: "Europe/Berlin" },
  { label: "Europe/Amsterdam", value: "Europe/Amsterdam" },
  { label: "Europe/Rome", value: "Europe/Rome" },
  { label: "Europe/Madrid", value: "Europe/Madrid" },
  { label: "Europe/Zurich", value: "Europe/Zurich" },
  { label: "Europe/Stockholm", value: "Europe/Stockholm" },
  { label: "Europe/Athens", value: "Europe/Athens" },
  { label: "Europe/Helsinki", value: "Europe/Helsinki" },
  { label: "Europe/Moscow", value: "Europe/Moscow" },
  { label: "Africa/Cairo", value: "Africa/Cairo" },
  { label: "Africa/Johannesburg", value: "Africa/Johannesburg" },
  { label: "Africa/Lagos", value: "Africa/Lagos" },
  { label: "Africa/Nairobi", value: "Africa/Nairobi" },
  { label: "Asia/Dubai", value: "Asia/Dubai" },
  { label: "Asia/Karachi", value: "Asia/Karachi" },
  { label: "Asia/Kolkata (IST)", value: "Asia/Kolkata" },
  { label: "Asia/Dhaka", value: "Asia/Dhaka" },
  { label: "Asia/Bangkok", value: "Asia/Bangkok" },
  { label: "Asia/Jakarta", value: "Asia/Jakarta" },
  { label: "Asia/Shanghai (CST)", value: "Asia/Shanghai" },
  { label: "Asia/Hong_Kong", value: "Asia/Hong_Kong" },
  { label: "Asia/Singapore", value: "Asia/Singapore" },
  { label: "Asia/Taipei", value: "Asia/Taipei" },
  { label: "Asia/Seoul", value: "Asia/Seoul" },
  { label: "Asia/Tokyo (JST)", value: "Asia/Tokyo" },
  { label: "Australia/Perth", value: "Australia/Perth" },
  { label: "Australia/Adelaide", value: "Australia/Adelaide" },
  { label: "Australia/Sydney", value: "Australia/Sydney" },
  { label: "Australia/Melbourne", value: "Australia/Melbourne" },
  { label: "Pacific/Auckland", value: "Pacific/Auckland" },
  { label: "Pacific/Fiji", value: "Pacific/Fiji" },
  { label: "America/Sao_Paulo", value: "America/Sao_Paulo" },
  { label: "America/Buenos_Aires", value: "America/Argentina/Buenos_Aires" },
  { label: "America/Mexico_City", value: "America/Mexico_City" },
  { label: "America/Bogota", value: "America/Bogota" },
  { label: "America/Lima", value: "America/Lima" },
  { label: "America/Santiago", value: "America/Santiago" },
];

export function detectUserTimezone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone;
  } catch {
    return "UTC";
  }
}
